server:
  port: 8080

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/books?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: lxz991203
      driver-class-name: com.mysql.cj.jdbc.Driver
  #      url: jdbc:mysql://127.0.0.1:3306/books?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#      username: root
#      password: test123456
  cache:
    ehcache:
      config: classpath:ehcache.xml
  thymeleaf:
    mode: LEGACYHTML5 #去除thymeleaf的html严格校验thymeleaf.mode=LEGACYHTML5
    cache: false # 是否开启模板缓存，默认true,建议在开发时关闭缓存,不然没法看到实时
  freemarker:
    template-loader-path: classpath:/templates #设定freemarker文件路径 默认为src/main/resources/templatestemplate-loader-path=classpath:/templates
    charset: UTF-8 # 模板编码

  profiles:
    include: crawl,website

  resources:
    cache:
      # 资源缓存时间，单位秒
      period: 604800
    # 开启gzip压缩
    chain:
      gzipped: true
      # 启用缓存
      cache: true


#  mvc:
#    static-path-pattern: /static/** #设定静态文件路径，js,css等
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: xyz.zinglizingli.books.po


#首页本站推荐小说配置
index:
  template: v2
  recBooks:
    - {bookName: The Mortal Cultivation of Immortals,bookAuthor: WangYu}



#mysql编码
mysql:
  charset: utf8mb4

books:
  #爬取小说数据的最低评分
  lowestScore: 6.0
  #小说的更新间隔（分）
  updatePeriod: 1

#爬取的网站名称类型 1：笔趣岛 ，2：笔趣塔,3:顶点小说  更多网站解析中，敬请期待
crawl:
  website:
    type: 2


pic:
  save:
    type: 1 #图片保存方式, 1不保存，使用网络图片 ，2本地保存
    path: /var/pic  #图片保存路径


search:
  schedule:
    isRunExcute: 0;


logging:
  config: classpath:logback-boot.xml


baidu:
  record:
    ids: 999999,888888


browser:
  cookie: SINAGLOBAL=5945695441587.724.1559298271897; __guid=109181959.2094437407894937900.1565875017257.2095; un=13560421324; _s_tentry=login.sina.com.cn; Apache=967339021599.2916.1567743040489; ULV=1567743040504:8:1:1:967339021599.2916.1567743040489:1566918991855; login_sid_t=d172b083637b1186ebcd624a1259a05f; cross_origin_proto=SSL; appkey=; SSOLoginState=1567744755; YF-Widget-G0=4a4609df0e4ef6187a7b4717d4e6cf12; wvr=6; WBtopGlobal_register_version=307744aa77dd5677; un=13560421324; SCF=AsBEGOtiUG1hPLyZCxI1FunZd9Hg9hWWkgyzcAZjG6AxlhR9sKuWXBhvg1TG9iDWygqPlKun5aazN3Jc6Rky8lQ.; SUB=_2A25wfnGoDeRhGeNL41YR9SnNwzyIHXVTCuRgrDV8PUJbmtANLRWgkW9NSM603g9LJN13ACge6_UUjKxvhLP4TXZi; SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9WFRg9065OjUyD0aaGsKRxPW5JpX5K-hUgL.Fo-f1hB7SKMp1h52dJLoI0qLxK-L1KqL1-eLxKMLB.-L122LxKMLB.-L122LxK-LBo5L12qLxKnLB-qLBoBLxKMLB.BL1K2t; SUHB=0XDVz5Bh1mkWFA; ALF=1599812938; UOR=,,sf.zinglizingli.xyz; monitor_count=13; webim_unReadCount=%7B%22time%22%3A1568285775036%2C%22dm_pub_total%22%3A1%2C%22chat_group_client%22%3A0%2C%22allcountNum%22%3A29%2C%22msgbox%22%3A0%7D